//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMaleabAlKorbV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Player
    {

        public int playerNo { get; set; }
        [Required]
        public string names { get; set; }
        [Required]
        [EmailAddress]
        public string emails { get; set; }
        [Required]
        public string passwords { get; set; }
        [Required]
        [RegularExpression(@"^(\+212|0)([ \-_/]*)(\d[ \-_/]*){9}$")]
        public string phone { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
