//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMaleabAlKorbV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservation
    {
        public int reservationNo { get; set; }
        [Required]
        public System.TimeSpan reservationTime { get; set; }
        [Required]
        public System.DateTime reservationDate { get; set; }
        public Nullable<System.DateTime> dateReservation { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        [Required]
        public Nullable<int> nbrPlayer { get; set; }
        [Required]
        public string Location { get; set; }
    }

   public enum location
    {
        Marrakech,
        CasaBlanca,
        Rabat,
        Tanger
    }
}
